const FRIENDS=["Asunoo","Waynn","Falkoo","Sloom","Yukoo","Ragnar","Nidiru","Zeeway"];
const QUESTIONS=["Qui est le plus gros Tryharder ?","Qui est le plus susceptible ?","Qui est le plus raciste ?","Qui est le plus gay ?","Qui est le plus drôle ?","Qui est le plus absent ?","Qui s'endort en voc ?","Qui est le plus guezzzzz au jeux ?","Qui se fait boost le plus ?","Qui est le plus gros toxico ?","Qui est le plus alcoolique ?","Qui bz le plus ?","Qui a le plus gros bodycount ?","Qui est le plus con ?","Qui est le plus brainrot ?","Qui se fait ragebait ?","Qui est trop 1er degrés ?","Qui est le plus susceptible de devenir riche ?","Qui est le plus susceptible de finir streamer ?","Qui survivrait le plus longtemps dans une apocalypse ?","Qui répond le plus vite aux messages ?","Qui répond le moins aux messages ?","Qui pourrait disparaître 6 mois sans prévenir ?","Qui serait le pire colocataire ?","Qui est le plus bordélique ?","Qui est le plus gros menteur ?","Qui est le plus susceptible de créer un drama ?","Qui est le plus susceptible de se faire bannir d'un serveur ?","Qui est le plus susceptible de devenir célèbre ?","Qui ferait le meilleur chef de groupe ?","Qui est le plus imprévisible ?","Qui est le plus susceptible de faire une dinguerie à 3h du matin ?","Qui est le plus susceptible d'oublier son propre anniversaire ?","Qui est le plus susceptible de ragequit ?","Qui est le plus compétitif pour absolument rien ?","Qui est le plus susceptible de changer de pseudo tous les mois ?","Qui est le plus gros procrastinateur ?","Qui a le plus de chances de se faire arnaquer par un scam évident ?","Qui est le plus susceptible de devenir un meme du groupe ?"];
const id=document.querySelector('#identity'),app=document.querySelector('#voteApp'),res=document.querySelector('#resultsApp');let current=null;
function go(id){document.getElementById(id).scrollIntoView({behavior:'smooth'});}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function renderIdentity(){id.innerHTML=`<label>QUI ES-TU ?</label><select class="select" id="who"><option value="">— sélectionner ton pseudo —</option>${FRIENDS.map(x=>`<option>${esc(x)}</option>`).join('')}</select>`;document.querySelector('#who').onchange=e=>{current=e.target.value;if(current)renderVote()};}
function renderVote(){app.classList.remove('hidden');app.innerHTML=`<div class="vote-head"><div><div class="counter" id="counter">0 / ${QUESTIONS.length} répondues</div><div class="bar"><span id="bar"></span></div></div><button class="btn" onclick="resetVote()">CHANGER DE PSEUDO</button></div><div class="questions">${QUESTIONS.map((q,i)=>`<article class="q"><div class="qnum">${String(i+1).padStart(2,'0')}</div><h3>${esc(q)}</h3><div class="opts">${FRIENDS.filter(x=>x!==current).map((x,j)=>`<div><input id="q${i}-${j}" type="radio" name="q${i}" value="${esc(x)}"><label for="q${i}-${j}">${esc(x)}</label></div>`).join('')}</div></article>`).join('')}</div><div class="actions"><button class="btn" onclick="submitVote()">VALIDER MES VOTES →</button></div>`;app.querySelectorAll('input').forEach(x=>x.onchange=update);}
function update(){const n=QUESTIONS.filter((_,i)=>app.querySelector(`input[name=q${i}]:checked`)).length;document.querySelector('#counter').textContent=`${n} / ${QUESTIONS.length} répondues`;document.querySelector('#bar').style.width=(n/QUESTIONS.length*100)+'%';}
function submitVote(){const a=QUESTIONS.map((_,i)=>app.querySelector(`input[name=q${i}]:checked`)?.value);if(a.includes(undefined)){alert('Toutes les questions doivent être répondues.');return;}let data=JSON.parse(localStorage.getItem('rawsfynzAllVotes')||'{}');data[current]={answers:a,submittedAt:new Date().toISOString()};localStorage.setItem('rawsfynzAllVotes',JSON.stringify(data));renderResults();go('results');alert('Votes enregistrés pour '+current+' !');}
function resetVote(){current=null;app.classList.add('hidden');renderIdentity();go('vote');}
function renderResults(){const data=JSON.parse(localStorage.getItem('rawsfynzAllVotes')||'{}');if(!Object.keys(data).length){res.innerHTML='<div class="empty">Aucun vote enregistré pour le moment.</div>';return;}let c=Object.fromEntries(FRIENDS.map(x=>[x,0]));Object.values(data).forEach(v=>v.answers.forEach(x=>c[x]++));const rows=Object.entries(c).sort((a,b)=>b[1]-a[1]);res.innerHTML=`<div class="empty" style="margin-bottom:15px">${Object.keys(data).length} participant(s) ont voté sur cet appareil.</div>`+rows.map((r,i)=>`<div class="rank"><span>#${i+1} — ${esc(r[0])}</span><strong>${r[1]} vote(s)</strong></div>`).join('');}
renderIdentity();renderResults();
