-- RAWSFYNZ CLUB — base Supabase pour votes partagés
-- À exécuter dans Supabase > SQL Editor.

create table if not exists public.participants (id bigint generated by default as identity primary key, name text unique not null);
create table if not exists public.questions (id bigint generated by default as identity primary key, question text not null, position int unique not null);
create table if not exists public.votes (id bigint generated by default as identity primary key, voter text not null references public.participants(name) on update cascade, question_id bigint not null references public.questions(id) on delete cascade, target text not null references public.participants(name) on update cascade, created_at timestamptz default now(), unique(voter, question_id));

insert into public.participants(name) values ('Asunoo'),('Waynn'),('Falkoo'),('Sloom'),('Yukoo'),('Ragnar'),('Nidiru'),('Zeeway') on conflict (name) do nothing;
insert into public.questions(question, position) values ('Qui est le plus gros Tryharder ?',1),
('Qui est le plus susceptible ?',2),
('Qui est le plus raciste ?',3),
('Qui est le plus gay ?',4),
('Qui est le plus drôle ?',5),
('Qui est le plus absent ?',6),
('Qui s''endort en voc ?',7),
('Qui est le plus guezzzzz au jeux ?',8),
('Qui se fait boost le plus ?',9),
('Qui est le plus gros toxico ?',10),
('Qui est le plus alcoolique ?',11),
('Qui bz le plus ?',12),
('Qui a le plus gros bodycount ?',13),
('Qui est le plus con ?',14),
('Qui est le plus brainrot ?',15),
('Qui se fait ragebait ?',16),
('Qui est trop 1er degrés ?',17),
('Qui est le plus susceptible de devenir riche ?',18),
('Qui est le plus susceptible de finir streamer ?',19),
('Qui survivrait le plus longtemps dans une apocalypse ?',20),
('Qui répond le plus vite aux messages ?',21),
('Qui répond le moins aux messages ?',22),
('Qui pourrait disparaître 6 mois sans prévenir ?',23),
('Qui serait le pire colocataire ?',24),
('Qui est le plus bordélique ?',25),
('Qui est le plus gros menteur ?',26),
('Qui est le plus susceptible de créer un drama ?',27),
('Qui est le plus susceptible de se faire bannir d''un serveur ?',28),
('Qui est le plus susceptible de devenir célèbre ?',29),
('Qui ferait le meilleur chef de groupe ?',30),
('Qui est le plus imprévisible ?',31),
('Qui est le plus susceptible de faire une dinguerie à 3h du matin ?',32),
('Qui est le plus susceptible d''oublier son propre anniversaire ?',33),
('Qui est le plus susceptible de ragequit ?',34),
('Qui est le plus compétitif pour absolument rien ?',35),
('Qui est le plus susceptible de changer de pseudo tous les mois ?',36),
('Qui est le plus gros procrastinateur ?',37),
('Qui a le plus de chances de se faire arnaquer par un scam évident ?',38),
('Qui est le plus susceptible de devenir un meme du groupe ?',39) on conflict (position) do update set question = excluded.question;

alter table public.participants enable row level security;
alter table public.questions enable row level security;
alter table public.votes enable row level security;

drop policy if exists "public read participants" on public.participants;
create policy "public read participants" on public.participants for select using (true);
drop policy if exists "public read questions" on public.questions;
create policy "public read questions" on public.questions for select using (true);
drop policy if exists "public read votes" on public.votes;
create policy "public read votes" on public.votes for select using (true);
drop policy if exists "public insert votes" on public.votes;
create policy "public insert votes" on public.votes for insert with check (voter in (select name from public.participants) and target in (select name from public.participants));
drop policy if exists "public update votes" on public.votes;
create policy "public update votes" on public.votes for update using (voter in (select name from public.participants)) with check (voter in (select name from public.participants) and target in (select name from public.participants));
